name: wtf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:

  animated_text_kit: ^4.2.1
  back_button_interceptor: ^5.0.1
  cached_network_image: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  extended_image: ^4.1.0
  file_picker:
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
#  flutter_login_facebook: ^1.1.0
  flutter_slidable: ^0.6.0
  flutter_spinkit:
  flutter_picker: ^2.0.2
  lottie: ^1.2.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  geolocator: ^7.6.0
  get: ^4.3.8
  get_it: ^3.0.3
  getwidget: ^2.0.4
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  http: ^0.13.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  maps_launcher: ^2.0.1
  multi_select_flutter: ^4.0.0
  multiselect_formfield: ^0.1.6
  numberpicker: ^2.1.1
  outline_gradient_button: ^2.0.0+1
  package_info: ^2.0.2
  photo_view: ^0.10.3
  pie_chart: ^5.0.0
  provider: ^5.0.0
  qr_code_scanner: ^0.5.2
  rating_dialog: ^2.0.1
  razorpay_flutter: ^1.2.7
  rename: ^1.3.1
#  rx_shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  simple_html_css: ^3.0.1
  slide_to_act: ^2.0.1
  staggered_grid_view_flutter:
  streaming_shared_preferences: ^2.0.0
  table_calendar: ^3.0.2
  url_launcher: ^6.0.10
  uuid: ^3.0.4
  video_player: ^2.1.12
  carousel_slider: ^4.0.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0
  firebase_core: ^1.0.2
  flutter_geocoder: ^0.2.2-nullsafety
  geocoding: ^2.0.1
#  flutter_fluid_slider: ^1.0.2
#  flutter_fluid_slider: ^1.0.3
#  flutter_google_places: ^0.3.0
  place_picker: ^0.9.19
  awesome_notifications:
  flutter_html: ^2.1.5
#  neumorphic: ^0.4.0
  flash: ^1.3.1
  jiffy: ^4.1.0
  flutter_native_image: ^0.0.6+1
  restart_app: ^1.1.0
  in_app_update: ^2.0.0
  otp_autofill: ^2.1.0
#  in_app_update: ^1.1.5
  flutter_screenutil: ^5.0.2
  jitsi_meet: ^4.0.0
  rolling_nav_bar: ^0.0.4
  status_change: ^2.0.0
  easy_gradient_text: ^1.0.0
  firebase_dynamic_links: ^2.0.10
  uni_links: ^0.5.1
  scaffold_gradient_background: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/gif/
    - assets/video/
    - assets/lottie/
    - assets/svg/
    - assets/svg/male/
    - assets/svg/female/
    - assets/svg/you_get/

  fonts:
    - family: Railway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
